// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupRolloutPrefs.privacy.purge_trackers.enabled", true);
user_pref("app.normandy.user_id", "1227b5aa-ce20-4d5a-a5a4-416d9d3292ce");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1600339503);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1600339502);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 4897);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1600339500);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{db14834f-e51e-40d8-89a0-07ae746e677c}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1600339503344");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1600343103344");
user_pref("browser.search.region", "IE");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.slowStartup.averageTime", 5974);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200831163820");
user_pref("browser.startup.homepage_override.mstone", "80.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1600339501);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1600339502277");
user_pref("distribution.iniFile.exists.appversion", "80.0.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "780ea441899c4b47a7236ae0cd203cfb");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "80.0.1");
user_pref("extensions.lastPlatformVersion", "80.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"f6ca9beb-2e8f-4128-a453-fe3b884c74aa\",\"formautofill@mozilla.org\":\"bb54b88a-4160-4dcd-9880-96ba80a59aa9\",\"screenshots@mozilla.org\":\"da8493a6-5cab-4a20-8bec-3161b1ca543f\",\"webcompat-reporter@mozilla.org\":\"9a3506d5-5155-4ff3-b3c4-fbea13a7fada\",\"webcompat@mozilla.org\":\"70b8ccaa-f7a3-4d3c-8409-a47401730c9a\",\"default-theme@mozilla.org\":\"14b9fd2f-ad3f-48d5-8655-2c637694897d\",\"google@search.mozilla.org\":\"e0ec9858-e6a2-4146-b791-9831e3e81681\",\"amazondotcom@search.mozilla.org\":\"484473ec-e969-447f-944e-8590766efd1b\",\"wikipedia@search.mozilla.org\":\"14e3a58c-5ab2-4768-aa11-d1a4ca506e75\",\"bing@search.mozilla.org\":\"da831803-47e3-49d6-9474-850b3dcf5fc7\",\"ddg@search.mozilla.org\":\"525d427b-3845-4360-a31a-9543ab9c4597\",\"ebay@search.mozilla.org\":\"5e72fe08-9175-42b9-9727-d1565189df06\"}");
user_pref("gfx.crash-guard.status.wmfvpxvideo", 2);
user_pref("gfx.crash-guard.wmfvpxvideo.appVersion", "80.0.1");
user_pref("gfx.crash-guard.wmfvpxvideo.deviceID", "0x1200");
user_pref("gfx.crash-guard.wmfvpxvideo.driverVersion", "23.21.13.8813");
user_pref("layers.mlgpu.sanity-test-failed", false);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.advanced-layers", true);
user_pref("sanity-test.device-id", "0x1200");
user_pref("sanity-test.driver-version", "23.21.13.8813");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20200831163820");
user_pref("sanity-test.webrender.force-disabled", false);
user_pref("security.sandbox.content.tempDirSuffix", "{774c5ff7-d202-4c98-a675-03f4a5ed48a5}");
user_pref("security.sandbox.plugin.tempDirSuffix", "{96f19bee-5d52-4953-99ae-c720fd631960}");
user_pref("toolkit.startup.last_success", 1600339495);
user_pref("toolkit.telemetry.cachedClientID", "5da83fa7-1daa-4e34-a875-9fb0b87fcd17");
user_pref("toolkit.telemetry.previousBuildID", "20200831163820");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
